### ISSUE TITLE
Contact 'Rena Mälaren'

### ISSUE THREAD

**Issue by gustafssonlinnea** [DH2413-G5/project-1#114]
A project that cleans the Mälaren sea in Stockholm. They wanted to collaborate! 

@sagapalmer got their contact information during ForskarFredag. 

Read more here: [https://www.renamalaren.com/](https://www.renamalaren.com/)

Here is the contact information from @sagapalmer :

tove.sefyrin@renamalaren.se
Vibrioscope.net (other organization)

**Comment by gustafssonlinnea** [comment]
Ask about: 
- what kinds of trash they find
- the amount/density of trash
- more ways to collaborate? As long as the scope is not too big

**Comment by sofiabergqvist** [comment]
Have sent an email to Rena Mälaren. Closing the issue to mark the start of the conversation.
