### ISSUE TITLE
Add electric scooters (~2020?)

### ISSUE THREAD

**Issue by gustafssonlinnea** [DH2413-G5/project-1#123]
Here is a free scooter model: https://assetstore.unity.com/packages/3d/props/exterior/electric-scooter-prop-171335 

The specific time we should ask Rena Mälaren about.

**Comment by sofiabergqvist** [comment]
The trash scene is, unsurprisingly, called "Trash" :) I tried to have a lot of the trash toward the end of the timeline be static meshes, so I hope the Quest will be able to handle it.
